name: eios
description: "EIOS MRSU"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  shared_preferences: ^2.2.2
  flutter_dotenv: ^6.0.0
  bloc: ^9.2.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  drift_dev: ^2.14.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - images/logo_mrsu.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo_mrsu.png"
  
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/logo_mrsu.png"
  
  remove_alpha_ios: true